"""
Manufacturing / Industry 4.0 scenario definition for Maestro City.
"""
from scenarios.base import ScenarioDefinition


def get_scenario() -> ScenarioDefinition:
    return ScenarioDefinition(
        id="manufacturing",
        name="Manufacturing & Industry 4.0",
        tagline="Keep factory floor controls and supply chains running during production incidents.",
        description=(
            "Simulate a manufacturing enterprise managing factory floor controls, SCADA systems, "
            "quality control, and supply chain operations. Respond to production incidents that "
            "directly impact output, quality, and worker safety compliance."
        ),
        industry="Manufacturing",
        icon="🏭",
        color="#8B5CF6",

        buildings=[
            {
                "id": "factory_floor",
                "type": "hospital",
                "name": "Factory Floor Control",
                "pos": {"x": 1, "y": 1, "w": 3, "h": 3},
                "status": "operational",
                "health": 100.0,
                "throughput": 88.0,
                "staffingLevel": 80.0,
                "trustLevel": 85.0,
                "dependencies": ["scada_platform", "orchestration_center", "supply_chain"],
                "queueDepth": 18,
                "recoveryCapacity": 55.0,
            },
            {
                "id": "quality_control",
                "type": "pharmacy",
                "name": "Quality Control System",
                "pos": {"x": 6, "y": 1, "w": 2, "h": 2},
                "status": "operational",
                "health": 100.0,
                "throughput": 85.0,
                "staffingLevel": 75.0,
                "trustLevel": 88.0,
                "dependencies": ["scada_platform", "factory_floor", "orchestration_center"],
                "queueDepth": 12,
                "recoveryCapacity": 65.0,
            },
            {
                "id": "scada_platform",
                "type": "cloud_datacenter",
                "name": "Cloud SCADA Platform",
                "pos": {"x": 14, "y": 1, "w": 3, "h": 3},
                "status": "operational",
                "health": 100.0,
                "throughput": 100.0,
                "staffingLevel": 60.0,
                "trustLevel": 95.0,
                "dependencies": [],
                "queueDepth": 0,
                "recoveryCapacity": 100.0,
            },
            {
                "id": "comms_hub",
                "type": "comms_hub",
                "name": "Plant Communications",
                "pos": {"x": 10, "y": 1, "w": 2, "h": 2},
                "status": "operational",
                "health": 100.0,
                "throughput": 90.0,
                "staffingLevel": 65.0,
                "trustLevel": 91.0,
                "dependencies": ["scada_platform"],
                "queueDepth": 6,
                "recoveryCapacity": 80.0,
            },
            {
                "id": "orchestration_center",
                "type": "orchestration_center",
                "name": "Industrial Automation Hub",
                "pos": {"x": 18, "y": 1, "w": 2, "h": 2},
                "status": "operational",
                "health": 100.0,
                "throughput": 87.0,
                "staffingLevel": 70.0,
                "trustLevel": 93.0,
                "dependencies": ["scada_platform", "comms_hub"],
                "queueDepth": 4,
                "recoveryCapacity": 85.0,
            },
            {
                "id": "supply_chain",
                "type": "staffing_hr",
                "name": "Supply Chain Management",
                "pos": {"x": 22, "y": 1, "w": 2, "h": 2},
                "status": "operational",
                "health": 100.0,
                "throughput": 80.0,
                "staffingLevel": 82.0,
                "trustLevel": 78.0,
                "dependencies": ["comms_hub"],
                "queueDepth": 22,
                "recoveryCapacity": 50.0,
            },
            {
                "id": "backup_infra",
                "type": "backup_infra",
                "name": "Backup Control Center",
                "pos": {"x": 26, "y": 1, "w": 2, "h": 2},
                "status": "operational",
                "health": 100.0,
                "throughput": 100.0,
                "staffingLevel": 50.0,
                "trustLevel": 84.0,
                "dependencies": [],
                "queueDepth": 0,
                "recoveryCapacity": 100.0,
            },
        ],

        agents=[
            {
                "id": "ops_coord",
                "type": "operations_coordinator",
                "name": "FORGE",
                "autonomyLevel": 2,
                "trustScore": 85.0,
                "status": "idle",
                "lastAction": "Production flow coordination and line optimization",
                "lastActionAt": 0.0,
                "actionsThisTick": 0,
                "currentBuildingId": "orchestration_center",
                "targetBuildingId": None,
            },
            {
                "id": "incident_resp",
                "type": "incident_response",
                "name": "TITAN",
                "autonomyLevel": 2,
                "trustScore": 90.0,
                "status": "idle",
                "lastAction": "Equipment failure and production incident response",
                "lastActionAt": 0.0,
                "actionsThisTick": 0,
                "currentBuildingId": "scada_platform",
                "targetBuildingId": None,
            },
            {
                "id": "compliance",
                "type": "compliance",
                "name": "PRISM",
                "autonomyLevel": 1,
                "trustScore": 78.0,
                "status": "idle",
                "lastAction": "ISO 9001, safety compliance and quality audit",
                "lastActionAt": 0.0,
                "actionsThisTick": 0,
                "currentBuildingId": "quality_control",
                "targetBuildingId": None,
            },
            {
                "id": "comms",
                "type": "communications",
                "name": "BEACON",
                "autonomyLevel": 2,
                "trustScore": 82.0,
                "status": "idle",
                "lastAction": "Plant communications and supply chain alerts",
                "lastActionAt": 0.0,
                "actionsThisTick": 0,
                "currentBuildingId": "comms_hub",
                "targetBuildingId": None,
            },
            {
                "id": "exec_strategy",
                "type": "executive_strategy",
                "name": "APEX",
                "autonomyLevel": 1,
                "trustScore": 88.0,
                "status": "idle",
                "lastAction": "Executive strategy for production and supply chain",
                "lastActionAt": 0.0,
                "actionsThisTick": 0,
                "currentBuildingId": "orchestration_center",
                "targetBuildingId": None,
            },
        ],

        workflows=[
            # Production orders: factory_floor <-> quality_control
            {"id": "wf-001", "type": "ehr_record", "sourceId": "factory_floor", "destId": "quality_control", "priority": "high", "status": "flowing", "automationEligible": True, "risk": 0.15, "progress": 0.10},
            {"id": "wf-002", "type": "ehr_record", "sourceId": "factory_floor", "destId": "quality_control", "priority": "high", "status": "flowing", "automationEligible": True, "risk": 0.20, "progress": 0.40},
            {"id": "wf-003", "type": "ehr_record", "sourceId": "factory_floor", "destId": "quality_control", "priority": "medium", "status": "flowing", "automationEligible": True, "risk": 0.10, "progress": 0.70},
            {"id": "wf-004", "type": "ehr_record", "sourceId": "factory_floor", "destId": "quality_control", "priority": "critical", "status": "flowing", "automationEligible": True, "risk": 0.30, "progress": 0.05},
            # Quality inspections: quality_control -> factory_floor
            {"id": "wf-005", "type": "prescription", "sourceId": "quality_control", "destId": "factory_floor", "priority": "high", "status": "flowing", "automationEligible": True, "risk": 0.25, "progress": 0.20},
            {"id": "wf-006", "type": "prescription", "sourceId": "quality_control", "destId": "factory_floor", "priority": "critical", "status": "flowing", "automationEligible": True, "risk": 0.35, "progress": 0.55},
            {"id": "wf-007", "type": "prescription", "sourceId": "quality_control", "destId": "factory_floor", "priority": "medium", "status": "flowing", "automationEligible": True, "risk": 0.15, "progress": 0.80},
            # Comm packets: plant communications
            {"id": "wf-008", "type": "comm_packet", "sourceId": "comms_hub", "destId": "factory_floor", "priority": "medium", "status": "flowing", "automationEligible": True, "risk": 0.05, "progress": 0.30},
            {"id": "wf-009", "type": "comm_packet", "sourceId": "comms_hub", "destId": "factory_floor", "priority": "low", "status": "flowing", "automationEligible": True, "risk": 0.05, "progress": 0.60},
            {"id": "wf-010", "type": "comm_packet", "sourceId": "comms_hub", "destId": "quality_control", "priority": "low", "status": "flowing", "automationEligible": True, "risk": 0.05, "progress": 0.15},
            {"id": "wf-011", "type": "comm_packet", "sourceId": "comms_hub", "destId": "orchestration_center", "priority": "medium", "status": "flowing", "automationEligible": True, "risk": 0.08, "progress": 0.45},
            # Approval requests
            {"id": "wf-012", "type": "approval_request", "sourceId": "factory_floor", "destId": "orchestration_center", "priority": "high", "status": "flowing", "automationEligible": True, "risk": 0.60, "progress": 0.25},
            {"id": "wf-013", "type": "approval_request", "sourceId": "quality_control", "destId": "orchestration_center", "priority": "medium", "status": "flowing", "automationEligible": True, "risk": 0.55, "progress": 0.50},
            # Supply chain requests
            {"id": "wf-014", "type": "staffing_request", "sourceId": "factory_floor", "destId": "supply_chain", "priority": "medium", "status": "flowing", "automationEligible": True, "risk": 0.10, "progress": 0.35},
            {"id": "wf-015", "type": "staffing_request", "sourceId": "factory_floor", "destId": "supply_chain", "priority": "high", "status": "flowing", "automationEligible": True, "risk": 0.20, "progress": 0.65},
            {"id": "wf-016", "type": "staffing_request", "sourceId": "quality_control", "destId": "supply_chain", "priority": "low", "status": "flowing", "automationEligible": True, "risk": 0.10, "progress": 0.10},
            # Escalations
            {"id": "wf-017", "type": "escalation", "sourceId": "orchestration_center", "destId": "scada_platform", "priority": "high", "status": "flowing", "automationEligible": True, "risk": 0.40, "progress": 0.20},
            # Failover commands
            {"id": "wf-018", "type": "failover_cmd", "sourceId": "backup_infra", "destId": "scada_platform", "priority": "low", "status": "flowing", "automationEligible": True, "risk": 0.05, "progress": 0.90},
            # Additional mixed workflows
            {"id": "wf-019", "type": "ehr_record", "sourceId": "factory_floor", "destId": "orchestration_center", "priority": "medium", "status": "flowing", "automationEligible": True, "risk": 0.18, "progress": 0.50},
            {"id": "wf-020", "type": "comm_packet", "sourceId": "comms_hub", "destId": "supply_chain", "priority": "low", "status": "flowing", "automationEligible": True, "risk": 0.05, "progress": 0.75},
        ],

        dependency_edges=[
            ("factory_floor", "scada_platform"),
            ("factory_floor", "orchestration_center"),
            ("factory_floor", "supply_chain"),
            ("quality_control", "scada_platform"),
            ("quality_control", "factory_floor"),
            ("quality_control", "orchestration_center"),
            ("comms_hub", "scada_platform"),
            ("orchestration_center", "scada_platform"),
            ("orchestration_center", "comms_hub"),
            ("supply_chain", "comms_hub"),
        ],

        vocabulary={
            "service_unit": "production unit",
            "primary_system": "Factory Floor",
            "secondary_system": "Quality Control",
            "workflow_type_primary": "production order",
            "workflow_type_secondary": "quality inspection",
            "staffing_role": "production staff",
            "incident_name": "Production Operations Incident",
            "outage_label": "Production Halt",
            "org_unit": "production line",
        },

        compliance_frameworks=["ISO 9001", "ISO 45001", "IEC 62443", "OSHA", "SOC2"],

        uipath_processes=[
            "Production_Incident_Escalation",
            "Safety_Approval_Chain",
            "Production_Crisis_Response",
            "Line_Emergency_Staffing",
            "Trust_Recovery_Protocol",
        ],

        outage_presets=[
            {
                "id": "scada_outage",
                "name": "SCADA Platform Outage",
                "buildingId": "scada_platform",
                "severity": "full",
                "description": "Cloud SCADA failure — factory floor control and quality systems lose connectivity",
            },
            {
                "id": "factory_partial",
                "name": "Factory Floor Degradation",
                "buildingId": "factory_floor",
                "severity": "partial",
                "description": "Partial factory floor control failure — production throughput reduced, quality at risk",
            },
            {
                "id": "supply_disruption",
                "name": "Supply Chain Disruption",
                "buildingId": "supply_chain",
                "severity": "partial",
                "description": "Supply chain management degradation — material flow disrupted, production scheduling impacted",
            },
        ],

        industry_context=(
            "Manufacturing operations require continuous uptime of factory floor controls, SCADA systems, "
            "and supply chain management. Downtime results in production losses, quality failures, and "
            "safety risks under ISO 9001, ISO 45001, and IEC 62443 standards."
        ),
    )
