"""Compact scenario specs. Structure (positions, workflows, agent roles) lives in factory.py.
Each spec supplies only the distinctive labeling: per-slot id/name/icon, agent names,
vocabulary, compliance, UiPath process names, and outage presets."""

SPECS = [
    {
        "id": "healthcare", "name": "Healthcare Enterprise", "icon": "🏥", "color": "#10B981",
        "industry": "Healthcare",
        "tagline": "Manage a hospital network's digital infrastructure under operational stress.",
        "description": "Simulate a large healthcare enterprise managing EHR systems, pharmacy dispensing, and clinical communications across a hospital network. Respond to system outages that directly impact patient safety and regulatory compliance.",
        "industry_context": "Healthcare enterprise operations require 24/7 availability across patient records, pharmacy dispensing, and clinical communications. Downtime directly impacts patient safety and regulatory compliance under HIPAA and Joint Commission standards.",
        "slots": {
            "primary": {"id": "hospital", "name": "City General Hospital", "icon": "🏥"},
            "secondary": {"id": "pharmacy", "name": "Central Pharmacy", "icon": "💊"},
            "infra": {"id": "cloud_datacenter", "name": "CloudCore Data Center", "icon": "☁️"},
            "comms": {"id": "comms_hub", "name": "Communications Hub", "icon": "📡"},
            "orchestration": {"id": "orchestration_center", "name": "Maestro Orchestration Center", "icon": "🎼"},
            "support": {"id": "staffing_hr", "name": "Staffing & Operations", "icon": "👥"},
            "failover": {"id": "backup_infra", "name": "Failover Infrastructure", "icon": "🛟"},
        },
        "agents": {"ops_coord": "ARIA", "incident_resp": "SENTINEL", "compliance": "VERITAS", "comms": "ECHO", "exec_strategy": "APEX"},
        "vocabulary": {"service_unit": "patient", "primary_system": "Hospital", "secondary_system": "Pharmacy", "workflow_type_primary": "EHR record", "workflow_type_secondary": "prescription", "staffing_role": "clinical staff", "incident_name": "Clinical Operations Incident", "outage_label": "System Outage", "org_unit": "department"},
        "compliance_frameworks": ["HIPAA", "SOC2", "Joint Commission"],
        "uipath_processes": ["Incident_Escalation", "Approval_Chain", "Crisis_Response", "Emergency_Staffing", "Trust_Recovery_Protocol"],
        "outage_presets": [
            {"id": "cloud_outage", "name": "Cloud Infrastructure Outage", "buildingId": "cloud_datacenter", "severity": "full", "description": "Simulates total cloud datacenter failure triggering cascade to hospital and pharmacy"},
            {"id": "hospital_partial", "name": "Hospital System Degradation", "buildingId": "hospital", "severity": "partial", "description": "Partial hospital system failure — EHR access impacted, ambulance rerouting required"},
            {"id": "comms_failure", "name": "Communications Hub Failure", "buildingId": "comms_hub", "severity": "full", "description": "Total communications hub failure — isolates hospital and pharmacy from orchestration"},
        ],
    },
    {
        "id": "financial_services", "name": "Financial Services", "icon": "📈", "color": "#3B82F6",
        "industry": "Financial Services",
        "tagline": "Keep trading floors and risk systems online during market volatility.",
        "description": "Simulate a financial services enterprise managing trading floors, risk management systems, and regulatory compliance infrastructure. Respond to trading outages that directly impact market positions, regulatory obligations, and counterparty trust.",
        "industry_context": "Financial services operations require sub-millisecond availability for trading systems and strict regulatory compliance under SOX, MiFID II, and Basel III. Downtime directly impacts market positions, regulatory obligations, and counterparty trust.",
        "slots": {
            "primary": {"id": "trading_floor", "name": "Trading Floor", "icon": "📈"},
            "secondary": {"id": "risk_management", "name": "Risk Management System", "icon": "🛡️"},
            "infra": {"id": "cloud_infra", "name": "Cloud Trading Infrastructure", "icon": "☁️"},
            "comms": {"id": "comms_hub", "name": "Market Data Communications", "icon": "📡"},
            "orchestration": {"id": "orchestration_center", "name": "Automation Orchestrator", "icon": "🎼"},
            "support": {"id": "compliance_center", "name": "Compliance & Regulatory", "icon": "⚖️"},
            "failover": {"id": "dr_site", "name": "Disaster Recovery Site", "icon": "🔁"},
        },
        "agents": {"ops_coord": "MERIDIAN", "incident_resp": "GUARDIAN", "compliance": "LEXIS", "comms": "HERALD", "exec_strategy": "NEXUS"},
        "vocabulary": {"service_unit": "transaction", "primary_system": "Trading Floor", "secondary_system": "Risk Management", "workflow_type_primary": "trade transaction", "workflow_type_secondary": "risk assessment", "staffing_role": "trading operations staff", "incident_name": "Trading Operations Incident", "outage_label": "Trading Halt", "org_unit": "desk"},
        "compliance_frameworks": ["SOX", "PCI-DSS", "MiFID II", "Basel III"],
        "uipath_processes": ["Trade_Incident_Escalation", "Regulatory_Approval_Chain", "Trading_Crisis_Response", "Desk_Coverage_Staffing", "Trust_Recovery_Protocol"],
        "outage_presets": [
            {"id": "cloud_outage", "name": "Cloud Infrastructure Outage", "buildingId": "cloud_infra", "severity": "full", "description": "Cloud trading infrastructure failure — triggers cascade to trading floor and risk systems"},
            {"id": "trading_halt", "name": "Trading Floor Halt", "buildingId": "trading_floor", "severity": "partial", "description": "Partial trading system failure — order routing degraded, position reconciliation impacted"},
            {"id": "comms_failure", "name": "Market Data Feed Failure", "buildingId": "comms_hub", "severity": "full", "description": "Market data communications failure — real-time pricing and risk feeds disrupted"},
        ],
    },
    {
        "id": "retail_ecommerce", "name": "Retail & E-commerce", "icon": "🛒", "color": "#F59E0B",
        "industry": "Retail & E-commerce",
        "tagline": "Keep orders flowing and payments processing during peak commerce events.",
        "description": "Simulate a retail e-commerce enterprise managing order management, payment processing, and fulfillment operations. Respond to outages that directly impact revenue, customer trust, and SLA compliance during high-traffic commerce events.",
        "industry_context": "E-commerce operations require continuous availability of payment processing, order management, and fulfillment systems. Downtime directly impacts revenue, customer trust, and SLA compliance under PCI-DSS and GDPR frameworks.",
        "slots": {
            "primary": {"id": "order_management", "name": "Order Management System", "icon": "📦"},
            "secondary": {"id": "payment_gateway", "name": "Payment Gateway", "icon": "💳"},
            "infra": {"id": "cloud_platform", "name": "Cloud Commerce Platform", "icon": "☁️"},
            "comms": {"id": "comms_hub", "name": "Customer Communications", "icon": "📨"},
            "orchestration": {"id": "orchestration_center", "name": "Commerce Automation Hub", "icon": "🎼"},
            "support": {"id": "fulfillment_ops", "name": "Warehouse & Fulfillment", "icon": "🚚"},
            "failover": {"id": "backup_infra", "name": "Backup Commerce Infrastructure", "icon": "🛟"},
        },
        "agents": {"ops_coord": "FLUX", "incident_resp": "SHIELD", "compliance": "CIPHER", "comms": "PULSE", "exec_strategy": "SUMMIT"},
        "vocabulary": {"service_unit": "customer order", "primary_system": "Order Management", "secondary_system": "Payment Gateway", "workflow_type_primary": "order record", "workflow_type_secondary": "payment transaction", "staffing_role": "fulfillment staff", "incident_name": "Commerce Operations Incident", "outage_label": "Service Disruption", "org_unit": "channel"},
        "compliance_frameworks": ["PCI-DSS", "GDPR", "SOC2 Type II", "ISO 27001"],
        "uipath_processes": ["Order_Incident_Escalation", "Payment_Approval_Chain", "Commerce_Crisis_Response", "Fulfillment_Emergency_Staffing", "Trust_Recovery_Protocol"],
        "outage_presets": [
            {"id": "cloud_outage", "name": "Cloud Platform Outage", "buildingId": "cloud_platform", "severity": "full", "description": "Cloud commerce platform failure — cascades to order management and payment systems"},
            {"id": "payment_failure", "name": "Payment Gateway Failure", "buildingId": "payment_gateway", "severity": "full", "description": "Payment processing failure — checkout blocked, revenue at risk"},
            {"id": "fulfillment_disruption", "name": "Warehouse System Disruption", "buildingId": "fulfillment_ops", "severity": "partial", "description": "Fulfillment system degradation — order processing slowed, SLA breaches imminent"},
        ],
    },
    {
        "id": "manufacturing", "name": "Manufacturing & Industry 4.0", "icon": "🏭", "color": "#8B5CF6",
        "industry": "Manufacturing",
        "tagline": "Keep factory floor controls and supply chains running during production incidents.",
        "description": "Simulate a manufacturing enterprise managing factory floor controls, SCADA systems, quality control, and supply chain operations. Respond to production incidents that directly impact output, quality, and worker safety compliance.",
        "industry_context": "Manufacturing operations require continuous uptime of factory floor controls, SCADA systems, and supply chain management. Downtime results in production losses, quality failures, and safety risks under ISO 9001, ISO 45001, and IEC 62443 standards.",
        "slots": {
            "primary": {"id": "factory_floor", "name": "Factory Floor Control", "icon": "🏭"},
            "secondary": {"id": "quality_control", "name": "Quality Control System", "icon": "🔬"},
            "infra": {"id": "scada_platform", "name": "Cloud SCADA Platform", "icon": "☁️"},
            "comms": {"id": "comms_hub", "name": "Plant Communications", "icon": "📡"},
            "orchestration": {"id": "orchestration_center", "name": "Industrial Automation Hub", "icon": "🎛️"},
            "support": {"id": "supply_chain", "name": "Supply Chain Management", "icon": "🚛"},
            "failover": {"id": "backup_infra", "name": "Backup Control Center", "icon": "🔁"},
        },
        "agents": {"ops_coord": "FORGE", "incident_resp": "TITAN", "compliance": "PRISM", "comms": "BEACON", "exec_strategy": "APEX"},
        "vocabulary": {"service_unit": "production unit", "primary_system": "Factory Floor", "secondary_system": "Quality Control", "workflow_type_primary": "production order", "workflow_type_secondary": "quality inspection", "staffing_role": "production staff", "incident_name": "Production Operations Incident", "outage_label": "Production Halt", "org_unit": "production line"},
        "compliance_frameworks": ["ISO 9001", "ISO 45001", "IEC 62443", "OSHA", "SOC2"],
        "uipath_processes": ["Production_Incident_Escalation", "Safety_Approval_Chain", "Production_Crisis_Response", "Line_Emergency_Staffing", "Trust_Recovery_Protocol"],
        "outage_presets": [
            {"id": "scada_outage", "name": "SCADA Platform Outage", "buildingId": "scada_platform", "severity": "full", "description": "Cloud SCADA failure — factory floor control and quality systems lose connectivity"},
            {"id": "factory_partial", "name": "Factory Floor Degradation", "buildingId": "factory_floor", "severity": "partial", "description": "Partial factory floor control failure — production throughput reduced, quality at risk"},
            {"id": "supply_disruption", "name": "Supply Chain Disruption", "buildingId": "supply_chain", "severity": "partial", "description": "Supply chain management degradation — material flow disrupted, production scheduling impacted"},
        ],
    },
    {
        "id": "energy", "name": "Energy & Utilities", "icon": "⚡", "color": "#EAB308",
        "industry": "Energy & Utilities",
        "tagline": "Keep the power grid stable and balanced as demand and faults surge.",
        "description": "Simulate an electric utility managing grid control, substations, and load dispatch under fluctuating demand and equipment faults. Respond to outages that risk cascading blackouts and regulatory penalties.",
        "industry_context": "Electric grid operations require continuous availability of control systems to maintain frequency stability and prevent cascading outages under NERC CIP and FERC reliability standards.",
        "slots": {
            "primary": {"id": "grid_control", "name": "Grid Control Room", "icon": "⚡"},
            "secondary": {"id": "substation", "name": "Substation Network", "icon": "🔌"},
            "infra": {"id": "grid_cloud", "name": "Cloud Grid Platform", "icon": "☁️"},
            "comms": {"id": "comms_hub", "name": "Grid Communications", "icon": "📡"},
            "orchestration": {"id": "orchestration_center", "name": "Energy Orchestration Hub", "icon": "🎛️"},
            "support": {"id": "field_ops", "name": "Field Operations", "icon": "🦺"},
            "failover": {"id": "backup_grid", "name": "Backup Grid Control", "icon": "🔁"},
        },
        "agents": {"ops_coord": "VOLT", "incident_resp": "SURGE", "compliance": "AUDIT", "comms": "RELAY", "exec_strategy": "ZENITH"},
        "vocabulary": {"service_unit": "megawatt-hour", "primary_system": "Grid Control Room", "secondary_system": "Substation Network", "workflow_type_primary": "load dispatch", "workflow_type_secondary": "fault isolation", "staffing_role": "grid operator", "incident_name": "Grid Stability Incident", "outage_label": "Grid Outage", "org_unit": "substation"},
        "compliance_frameworks": ["NERC CIP", "FERC Order 2222", "IEC 62351"],
        "uipath_processes": ["Grid_Incident_Escalation", "Grid_Approval_Chain", "Grid_Crisis_Response", "Operator_Coverage_Staffing", "Trust_Recovery_Protocol"],
        "outage_presets": [
            {"id": "grid_cloud_outage", "name": "Grid Platform Outage", "buildingId": "grid_cloud", "severity": "full", "description": "Cloud grid platform failure — control room and substations lose telemetry and dispatch"},
            {"id": "control_partial", "name": "Grid Control Degradation", "buildingId": "grid_control", "severity": "partial", "description": "Partial control room failure — load balancing degraded, frequency drift risk"},
            {"id": "comms_failure", "name": "Grid Communications Failure", "buildingId": "comms_hub", "severity": "full", "description": "Grid communications failure — SCADA telemetry to substations disrupted"},
        ],
    },
    {
        "id": "aviation", "name": "Aviation Operations", "icon": "✈️", "color": "#0EA5E9",
        "industry": "Aviation",
        "tagline": "Keep flights moving and the airport safe through operational disruptions.",
        "description": "Simulate an airport operations enterprise managing flight movements, baggage handling, and ground operations. Respond to disruptions that risk ground stops, safety incidents, and cascading delays.",
        "industry_context": "Airport operations require continuous availability of flight movement, baggage, and ground systems. Downtime risks ground stops, safety incidents, and cascading delays under FAA Part 139, ICAO, and TSA requirements.",
        "slots": {
            "primary": {"id": "airport_ops", "name": "Airport Operations Center", "icon": "🛫"},
            "secondary": {"id": "baggage", "name": "Baggage Handling System", "icon": "🧳"},
            "infra": {"id": "flight_cloud", "name": "Cloud Flight Platform", "icon": "☁️"},
            "comms": {"id": "comms_hub", "name": "ATC Communications", "icon": "📡"},
            "orchestration": {"id": "orchestration_center", "name": "Operations Orchestration", "icon": "🗼"},
            "support": {"id": "ground_crew", "name": "Ground Crew Staffing", "icon": "🦺"},
            "failover": {"id": "backup_ops", "name": "Backup Operations Center", "icon": "🔁"},
        },
        "agents": {"ops_coord": "TOWER", "incident_resp": "FALCON", "compliance": "AEGIS", "comms": "RELAY", "exec_strategy": "SUMMIT"},
        "vocabulary": {"service_unit": "flight", "primary_system": "Airport Operations", "secondary_system": "Baggage Handling", "workflow_type_primary": "flight movement", "workflow_type_secondary": "baggage routing", "staffing_role": "ground crew", "incident_name": "Flight Operations Incident", "outage_label": "Ground Stop", "org_unit": "terminal"},
        "compliance_frameworks": ["FAA Part 139", "ICAO Annex 14", "TSA"],
        "uipath_processes": ["Flight_Incident_Escalation", "Safety_Approval_Chain", "Aviation_Crisis_Response", "Crew_Coverage_Staffing", "Trust_Recovery_Protocol"],
        "outage_presets": [
            {"id": "flight_cloud_outage", "name": "Flight Platform Outage", "buildingId": "flight_cloud", "severity": "full", "description": "Cloud flight platform failure — ops center and baggage systems lose flight data"},
            {"id": "ops_partial", "name": "Operations Center Degradation", "buildingId": "airport_ops", "severity": "partial", "description": "Partial ops center failure — gate assignment and sequencing degraded"},
            {"id": "atc_failure", "name": "ATC Communications Failure", "buildingId": "comms_hub", "severity": "full", "description": "ATC communications failure — ground stop risk, flight movements halted"},
        ],
    },
    {
        "id": "telecom", "name": "Telecommunications", "icon": "📶", "color": "#14B8A6",
        "industry": "Telecommunications",
        "tagline": "Keep the network up and subscribers connected through service incidents.",
        "description": "Simulate a telecom carrier managing the core network, subscriber billing, and customer service. Respond to network incidents that risk mass service outages, SLA breaches, and subscriber churn.",
        "industry_context": "Telecom operations require continuous availability of the core network, billing, and customer service systems. Downtime risks mass service outages, SLA breaches, and regulatory penalties under FCC and GDPR rules.",
        "slots": {
            "primary": {"id": "noc", "name": "Network Operations Center", "icon": "📶"},
            "secondary": {"id": "billing", "name": "Subscriber Billing", "icon": "🧾"},
            "infra": {"id": "core_network", "name": "Cloud Core Network", "icon": "☁️"},
            "comms": {"id": "comms_hub", "name": "Customer Communications", "icon": "📨"},
            "orchestration": {"id": "orchestration_center", "name": "Service Orchestration", "icon": "🎛️"},
            "support": {"id": "field_tech", "name": "Field Technician Staffing", "icon": "🦺"},
            "failover": {"id": "backup_core", "name": "Backup Core Network", "icon": "🔁"},
        },
        "agents": {"ops_coord": "SIGNAL", "incident_resp": "SENTRY", "compliance": "WARDEN", "comms": "BROADCAST", "exec_strategy": "PINNACLE"},
        "vocabulary": {"service_unit": "subscriber session", "primary_system": "Network Operations", "secondary_system": "Billing", "workflow_type_primary": "call routing", "workflow_type_secondary": "billing record", "staffing_role": "field technician", "incident_name": "Network Operations Incident", "outage_label": "Service Outage", "org_unit": "region"},
        "compliance_frameworks": ["FCC", "GDPR", "SOC2", "ISO 27001"],
        "uipath_processes": ["Network_Incident_Escalation", "Billing_Approval_Chain", "Network_Crisis_Response", "Tech_Coverage_Staffing", "Trust_Recovery_Protocol"],
        "outage_presets": [
            {"id": "core_outage", "name": "Core Network Outage", "buildingId": "core_network", "severity": "full", "description": "Cloud core network failure — NOC and billing lose connectivity, mass outage risk"},
            {"id": "noc_partial", "name": "NOC Degradation", "buildingId": "noc", "severity": "partial", "description": "Partial NOC failure — traffic engineering degraded, congestion building"},
            {"id": "comms_failure", "name": "Customer Comms Failure", "buildingId": "comms_hub", "severity": "full", "description": "Customer communications failure — outage notifications and support disrupted"},
        ],
    },
]
